use customer_behaviour;
select * from mytable;

-- Q1. What is the total revenue generated by male vs. female mytables?
SELECT gender, SUM(purchase_amount) AS total_revenue
FROM mytable
GROUP BY gender;


-- Q2. Which mytables used a discount but still spent more than the average purchase amount? 
SELECT * FROM mytable
WHERE discount_applied="Yes"
AND purchase_amount>(
SELECT AVG(purchase_amount) FROM mytable
)


-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, avg(review_rating) as "Average item rating"
from mytable
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type,
       AVG(purchase_amount) AS average_purchase_amount
FROM mytable
WHERE shipping_type IN ('Express', 'Standard')
GROUP BY shipping_type;

-- Q5. Do subscribed mytables spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
select count(customer_id) as total_customers, subscription_status, sum(purchase_amount) as "total_revenue", avg(purchase_amount) as "average_revenue"
from mytable
group by subscription_status
order by total_revenue, average_revenue desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, 
count(case when discount_applied='Yes' then 1 end) *100.0 / count(*) as 'percentage_of_purchase'
from mytable
group by item_purchased
order by percentage_of_purchase desc
limit 5;

-- Q7. Segment mytables into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
select count(customer_id),
case 
when previous_purchases = 0 then 'new'
when previous_purchases between 1 and 5 then 'returning'
else 'loyal'
end as 'customer_segment'
from mytable
group by customer_segment;



-- Q8. What are the top 3 most purchased products within each category? 
SELECT category,
       item_purchased,
       purchase_count
FROM (

    SELECT category,
           item_purchased,
           COUNT(*) AS purchase_count,

           ROW_NUMBER() OVER(
               PARTITION BY category
               ORDER BY COUNT(*) DESC
           ) AS rn

    FROM mytable

    GROUP BY category, item_purchased

) AS ranked_products

WHERE rn <= 3;
 
-- Q9. Are mytables who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM mytable
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q10. What is the revenue contribution of each age group? 
select age_group, sum(purchase_amount) as 'total_revenue'
from mytable
group by age_group;
